# Generated by Django 5.0.6 on 2026-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Штрихкод')),
                ('calories', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Калории, ккал')),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Белки, г')),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Жиры, г')),
                ('carbs', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Углеводы, г')),
                ('fiber', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Клетчатка, г')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Пользовательский продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
    ]
