# Generated by Django 5.0.6 on 2026-04-01 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Приемы пищи',
                'ordering': ['-date', 'meal_type__order'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('unit', models.CharField(choices=[('g', 'грамм'), ('ml', 'миллилитр'), ('pcs', 'штук')], default='g', max_length=5)),
                ('calories', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('icon', models.CharField(default='restaurant', max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тип приема пищи',
                'verbose_name_plural': 'Типы приемов пищи',
                'ordering': ['order'],
            },
        ),
    ]
