# Generated by Django 5.0.6 on 2026-04-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(default='🥗', max_length=10, verbose_name='Иконка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration_days', models.IntegerField(default=7, verbose_name='Длительность (дней)')),
                ('calories_range', models.CharField(max_length=50, verbose_name='Диапазон калорий')),
                ('color', models.CharField(default='#FF6B35', max_length=20, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Диета',
                'verbose_name_plural': 'Диеты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('instructions', models.TextField(verbose_name='Приготовление')),
                ('prep_time', models.PositiveIntegerField(default=30, verbose_name='Время приготовления (мин)')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Калории')),
                ('protein', models.PositiveIntegerField(default=0, verbose_name='Белки')),
                ('fat', models.PositiveIntegerField(default=0, verbose_name='Жиры')),
                ('carbs', models.PositiveIntegerField(default=0, verbose_name='Углеводы')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=20, verbose_name='Тип приема')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.diet')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='День')),
                ('breakfast', models.TextField(verbose_name='Завтрак')),
                ('lunch', models.TextField(verbose_name='Обед')),
                ('dinner', models.TextField(verbose_name='Ужин')),
                ('snack', models.TextField(blank=True, verbose_name='Перекус')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='recipes.diet')),
            ],
            options={
                'verbose_name': 'Дневной план',
                'verbose_name_plural': 'Дневные планы',
                'ordering': ['day_number'],
                'unique_together': {('diet', 'day_number')},
            },
        ),
    ]
